apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qrmenu
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ingress.yaml
  - celery-worker.yaml
  - celery-beat.yaml
  - hpa.yaml
images:
  - name: qrmenu/api
    newTag: latest
