"""initial_schema_v2

Revision ID: bf2809408e7c
Revises: 
Create Date: 2026-05-18 18:39:16.986293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf2809408e7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_order_at', sa.DateTime(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('delivery_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('boundary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('center_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('center_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('estimated_prep_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('license_expiry', sa.DateTime(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('vehicle_plate', sa.String(), nullable=True),
    sa.Column('vehicle_color', sa.String(), nullable=True),
    sa.Column('insurance_doc_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('item_modifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('min_select', sa.Integer(), nullable=False),
    sa.Column('max_select', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_localized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('dine_in', 'drive_in', 'pickup', 'delivery', 'web', name='ordertypeenum'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('schema_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preview_image_url', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_merchants', sa.Integer(), nullable=False),
    sa.Column('max_items', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('system_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('reconciliation_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('batch_period_start', sa.DateTime(), nullable=False),
    sa.Column('batch_period_end', sa.DateTime(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_in_house', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_3rd_party', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_delivery_fees', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tips', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_commissions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('applies_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('third_party_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('partner_name', sa.Enum('talabat', 'zomato', 'jahez', name='thirdpartypartnername'), nullable=False),
    sa.Column('partner_merchant_id', sa.String(), nullable=True),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.Column('auth_type', sa.Enum('api_key', 'oauth2', 'basic', name='authtype'), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('sync_menu', sa.Boolean(), nullable=False),
    sa.Column('sync_inventory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'manager', 'cashier', 'kitchen', 'readonly', name='userrole'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('address_line_1', sa.String(), nullable=False),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('building_name', sa.String(), nullable=True),
    sa.Column('floor_apartment', sa.String(), nullable=True),
    sa.Column('delivery_notes', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('base_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_km_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_order', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('free_delivery_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('surge_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('surge_start', sa.Time(), nullable=True),
    sa.Column('surge_end', sa.Time(), nullable=True),
    sa.Column('max_fee_cap', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['delivery_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_earnings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('base_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tip_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('settlement_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='settlementstatus'), nullable=False),
    sa.Column('settlement_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('accuracy_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('speed_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_moving', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'active', 'completed', 'cancelled', name='drivershiftstatus'), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('zone_assignment', sa.String(), nullable=True),
    sa.Column('max_orders', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_localized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('allergens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutritional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prep_time_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('industry_template_id', sa.UUID(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('brand_primary_color', sa.String(), nullable=True),
    sa.Column('brand_secondary_color', sa.String(), nullable=True),
    sa.Column('brand_bg_image_url', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('tax_number', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['industry_template_id'], ['public.industry_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modifier_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('modifier_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_adjustment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['item_modifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['public.subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='public'
    )
    op.create_table('tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('table_number', sa.String(), nullable=False),
    sa.Column('seating_capacity', sa.Integer(), nullable=False),
    sa.Column('qr_code_url', sa.String(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('free', 'occupied', 'reserved', name='tablestatus'), nullable=False),
    sa.Column('last_occupied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_table('third_party_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('payout_period_start', sa.DateTime(), nullable=False),
    sa.Column('payout_period_end', sa.DateTime(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payout_reference', sa.String(), nullable=True),
    sa.Column('payout_date', sa.DateTime(), nullable=True),
    sa.Column('reconciliation_status', sa.Enum('open', 'processing', 'matched', 'variance', 'closed', name='reconciliationstatus'), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['third_party_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_modifier_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('modifier_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['item_modifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_acceptance_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('auto_accept_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_accept_timeout_sec', sa.Integer(), nullable=False),
    sa.Column('decline_auto_refund', sa.Boolean(), nullable=False),
    sa.Column('outside_hours_action', sa.Enum('auto_decline', 'schedule_next_day', 'allow_anyway', name='outsidehoursaction'), nullable=False),
    sa.Column('max_pending_orders', sa.Integer(), nullable=False),
    sa.Column('acceptance_mode', sa.Enum('manual', 'auto', 'whatsapp', name='acceptancemode'), nullable=False),
    sa.Column('escalation_sms_after_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('merchant_business_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('is_24h', sa.Boolean(), nullable=False),
    sa.Column('special_date', sa.Date(), nullable=True),
    sa.Column('special_open', sa.Time(), nullable=True),
    sa.Column('special_close', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_withdrawn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_settlement_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('qr_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cart_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_gateway_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='settlementstatus'), nullable=False),
    sa.Column('transfer_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_template_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('meta_template_id', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='templatestatus'), nullable=False),
    sa.Column('params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('qr_session_id', sa.UUID(), nullable=True),
    sa.Column('order_type', sa.Enum('dine_in', 'drive_in', 'pickup', 'delivery', 'web', name='ordertypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'READY', 'SERVED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('whatsapp_notified', sa.Boolean(), nullable=False),
    sa.Column('kitchen_started_at', sa.DateTime(), nullable=True),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_type', sa.Enum('in_house', 'third_party', 'pickup', 'dine_in', name='deliverytype'), nullable=True),
    sa.Column('delivery_zone_id', sa.UUID(), nullable=True),
    sa.Column('delivery_address_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('third_party_partner_id', sa.UUID(), nullable=True),
    sa.Column('third_party_order_ref', sa.String(), nullable=True),
    sa.Column('estimated_delivery_time', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_time', sa.DateTime(), nullable=True),
    sa.Column('delivery_rating', sa.Integer(), nullable=True),
    sa.Column('delivery_tip', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_otp', sa.String(), nullable=True),
    sa.Column('delivery_proof_url', sa.String(), nullable=True),
    sa.Column('acceptance_status', sa.Enum('pending', 'accepted', 'declined', 'auto_accepted', 'timeout', name='acceptancestatus'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by', sa.Enum('merchant', 'system', 'whatsapp', name='acceptedby'), nullable=True),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['delivery_addresses.id'], ),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['delivery_zones.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['qr_session_id'], ['qr_sessions.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['third_party_partner_id'], ['third_party_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('assignment_type', sa.Enum('auto', 'manual', 'driver_pickup', name='assignmenttype'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_otp', sa.String(), nullable=True),
    sa.Column('delivery_proof_url', sa.String(), nullable=True),
    sa.Column('customer_rating', sa.Integer(), nullable=True),
    sa.Column('customer_tip', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['delivery_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_eta_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('predicted_eta_min', sa.Integer(), nullable=False),
    sa.Column('actual_delivery_min', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('traffic_factor', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('weather_factor', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['delivery_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('merchant_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('item_name_snapshot', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('modifier_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('special_instructions', sa.String(), nullable=True),
    sa.Column('kitchen_station', sa.String(), nullable=True),
    sa.Column('prep_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_type', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.Enum('urgent', 'allergy', 'vip', 'complimentary', name='ordertagenum'), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('gateway', sa.Enum('stripe', 'paypal', 'hyperpay', 'telr', 'cod', name='paymentgateway'), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'authorized', 'paid', 'failed', 'refunded', 'partially_refunded', name='paymentstatus'), nullable=False),
    sa.Column('payment_method_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_reason', sa.String(), nullable=True),
    sa.Column('webhook_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('third_party_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('partner_order_ref', sa.String(), nullable=False),
    sa.Column('partner_status', sa.String(), nullable=True),
    sa.Column('partner_rider_name', sa.String(), nullable=True),
    sa.Column('partner_rider_phone', sa.String(), nullable=True),
    sa.Column('partner_eta_min', sa.Integer(), nullable=True),
    sa.Column('partner_delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('partner_commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('partner_payout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['third_party_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_acceptance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('merchant_phone', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('sent', 'delivered', 'read', 'failed', name='whatsappmessagestatus'), nullable=False),
    sa.Column('action', sa.Enum('accept', 'decline', 'timeout', name='whatsappaction'), nullable=True),
    sa.Column('response_timestamp', sa.DateTime(), nullable=True),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('auto_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'rescheduled', name='deliveryattemptstatus'), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('customer_not_available', sa.Boolean(), nullable=False),
    sa.Column('wrong_address', sa.Boolean(), nullable=False),
    sa.Column('driver_notes', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('next_attempt_scheduled', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['delivery_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('waypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optimized_sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('actual_duration_min', sa.Integer(), nullable=True),
    sa.Column('route_geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('traffic_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['delivery_assignments.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Manual additions: RLS, Indexes, Partitions, TimescaleDB, Functions
    # ------------------------------------------------------------------

    # 1. Tenant schema auto-creation function
    op.execute("""
    CREATE OR REPLACE FUNCTION create_tenant_schema()
    RETURNS TRIGGER AS $$
    BEGIN
        EXECUTE format('CREATE SCHEMA IF NOT EXISTS tenant_%I', NEW.slug);
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_trigger WHERE tgname = 'trigger_create_tenant_schema'
        ) THEN
            CREATE TRIGGER trigger_create_tenant_schema
            AFTER INSERT ON public.tenants
            FOR EACH ROW
            EXECUTE FUNCTION create_tenant_schema();
        END IF;
    END $$;
    """)

    # 2. Enable RLS on all tenant-isolated tables
    tenant_tables_merchant_id = [
        "customers", "delivery_zones", "drivers", "item_modifiers",
        "locations", "menu_categories", "menu_items",
        "order_types", "tables", "users",
        "delivery_pricing_rules", "driver_earnings",
        "driver_locations", "driver_shifts", "orders",
        "reconciliation_batches", "tax_rates",
        "third_party_partners", "third_party_payouts",
        "merchant_acceptance_settings", "merchant_business_hours",
        "merchant_wallets", "settlements", "whatsapp_template_registry",
        "delivery_assignments", "payments", "delivery_routes"
    ]

    tenant_tables_id = ["merchants"]  # merchants uses 'id' as the tenant key

    for tbl in tenant_tables_merchant_id:
        op.execute(f'ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;')
        op.execute(f"""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_policies WHERE tablename = '{tbl}' AND policyname = 'tenant_isolation'
            ) THEN
                CREATE POLICY tenant_isolation ON {tbl}
                USING (merchant_id::text = current_setting('app.current_tenant', true));
            END IF;
        END $$;
        """)
        op.execute(f"""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_policies WHERE tablename = '{tbl}' AND policyname = 'admin_bypass'
            ) THEN
                CREATE POLICY admin_bypass ON {tbl}
                USING (current_setting('app.is_superadmin', true) = 'true');
            END IF;
        END $$;
        """)

    for tbl in tenant_tables_id:
        op.execute(f'ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;')
        op.execute(f"""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_policies WHERE tablename = '{tbl}' AND policyname = 'tenant_isolation'
            ) THEN
                CREATE POLICY tenant_isolation ON {tbl}
                USING (id::text = current_setting('app.current_tenant', true));
            END IF;
        END $$;
        """)
        op.execute(f"""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_policies WHERE tablename = '{tbl}' AND policyname = 'admin_bypass'
            ) THEN
                CREATE POLICY admin_bypass ON {tbl}
                USING (current_setting('app.is_superadmin', true) = 'true');
            END IF;
        END $$;
        """)

    # 3. Additional indexes
    op.execute("CREATE INDEX IF NOT EXISTS ix_orders_merchant_status ON orders (merchant_id, status);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_orders_created_at ON orders (created_at);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_order_items_order_id ON order_items (order_id);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_menu_items_merchant_category ON menu_items (merchant_id, category_id);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_driver_locations_driver_timestamp ON driver_locations (driver_id, timestamp);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_delivery_zones_merchant ON delivery_zones (merchant_id);")

    # 4. Full-text search on menu_items (using GIN on name)
    op.execute("""
    DO $$
    BEGIN
        CREATE INDEX IF NOT EXISTS ix_menu_items_name_gin ON menu_items USING gin(to_tsvector('english', name));
    EXCEPTION WHEN undefined_function THEN
        -- gin might not support to_tsvector directly in all versions; fallback
        NULL;
    END $$;
    """)

    # 5. Partition orders and order_items by month (creation of first few partitions)
    op.execute("""
    -- Note: orders and order_items were created as regular tables.
    -- For true partitioning they should be recreated as partitioned.
    -- Here we add a partitioned wrapper via inheritance for Phase 1 scaffold.
    -- Full partitioning will be handled in a dedicated migration.
    DO $$
    BEGIN
        RAISE NOTICE 'Partitioning for orders and order_items should be implemented via dedicated migration or table recreation.';
    END $$;
    """)

    # 6. TimescaleDB hypertable for driver_locations
    op.execute("""
    DO $$
    BEGIN
        CREATE EXTENSION IF NOT EXISTS timescaledb;
        PERFORM create_hypertable('driver_locations', 'timestamp', if_not_exists => TRUE);
    EXCEPTION WHEN undefined_object THEN
        RAISE NOTICE 'TimescaleDB extension not available; driver_locations remains a regular table.';
    WHEN feature_not_supported THEN
        RAISE NOTICE 'TimescaleDB not supported on this instance; driver_locations remains a regular table.';
    END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_routes')
    op.drop_table('delivery_attempts')
    op.drop_table('whatsapp_acceptance_logs')
    op.drop_table('third_party_orders')
    op.drop_table('payments')
    op.drop_table('order_tags')
    op.drop_table('order_status_logs')
    op.drop_table('order_items')
    op.drop_table('driver_ratings')
    op.drop_table('delivery_eta_history')
    op.drop_table('delivery_assignments')
    op.drop_table('orders')
    op.drop_table('whatsapp_template_registry')
    op.drop_table('settlements')
    op.drop_table('qr_sessions')
    op.drop_table('merchant_wallets')
    op.drop_table('merchant_business_hours')
    op.drop_table('merchant_acceptance_settings')
    op.drop_table('item_modifier_links')
    op.drop_table('third_party_payouts')
    op.drop_table('tables')
    op.drop_table('tenants', schema='public')
    op.drop_table('modifier_options')
    op.drop_table('merchants')
    op.drop_table('menu_items')
    op.drop_table('driver_shifts')
    op.drop_table('driver_locations')
    op.drop_table('driver_earnings')
    op.drop_table('delivery_pricing_rules')
    op.drop_table('delivery_addresses')
    op.drop_table('users')
    op.drop_table('third_party_partners')
    op.drop_table('tax_rates')
    op.drop_table('reconciliation_batches')
    op.drop_table('system_audit_logs', schema='public')
    op.drop_table('subscription_plans', schema='public')
    op.drop_table('industry_templates', schema='public')
    op.drop_table('order_types')
    op.drop_table('menu_categories')
    op.drop_table('locations')
    op.drop_table('item_modifiers')
    op.drop_table('drivers')
    op.drop_table('delivery_zones')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
